---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation template to build an AWS CodeCommit repo and associated resources
Parameters:
  RepositoryName:
    Description: CodeCommit repository name
    Type: String
    Default: CFNDemoRepo
  BranchName:
    Description: CodeCommit branch name
    Type: String
    Default: master
  ProjectName:
    Description: CodeBuild project name
    Type: String
    Default: DemoProject
Resources:
  DemoSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "DemoTopic"
  DemoRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryDescription: a repo for CloudFormation demo source code
      Triggers:
        - Name: MasterTrigger
          DestinationArn:
            Ref: DemoSNSTopic
          Branches:
            - Master
          Events:
            - all
  CodeCommitPowerUserGroup:
    Type: AWS::IAM::Group
    DependsOn: CodeCommitPowerUser
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodeCommitPowerUser"
  CodeCommitPowerUser:
    Type: AWS::IAM::User
    Properties:
      Path: "/"
      LoginProfile:
        Password: myP@ssW0rd
  CFNKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: CodeCommitPowerUser
  AddUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    DependsOn: CodeCommitPowerUserGroup
    Properties:
      GroupName:
        Ref: CodeCommitPowerUserGroup
      Users:
        - Ref: CodeCommitPowerUser
Outputs:
  AccessKeyId:
    Value: !Ref CFNKeys
    Description: AccessKeyId
  SecretAccessKey:
    Value: !GetAtt CFNKeys.SecretAccessKey
    Description: SecretAccessKey
  RepositoryName:
    Value: !Ref RepositoryName
    Description: CodeCommit repository name
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "repository-name"]]
  BranchName:
    Value: !Ref BranchName
    Description: CodeCommit branch name
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "branch-name"]]
