---
version: 0.2

phases:
  install:
    commands:
      - pip install yamllint
      - yes | yum install php-jsonlint
  build:
    commands:
      - jsonlint-php dynamo_config.json # json lint the config
      - yamllint -d relaxed dynamo.yaml # yaml lint the template
      - aws cloudformation validate-template --template-body file://dynamo.yaml
